DROP TABLE IF EXISTS EMPLOYEE;
DROP TABLE IF EXISTS POST;
DROP TABLE IF EXISTS PHOTO;

CREATE TABLE POST(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL
);

CREATE TABLE PHOTO(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	CONTENTTYPE VARCHAR(40) NOT NULL,
	PHOTO BLOB NOT NULL
);

CREATE TABLE EMPLOYEE(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	EMPID VARCHAR(10) NOT NULL,
	NAME VARCHAR(40) NOT NULL,
	AGE TINYINT,
	GENDER VARCHAR(8) NOT NULL,
	PHOTOID INT,
	ZIP VARCHAR(10),
	PREF TINYINT,
	ADDRESS VARCHAR(100),
	POSTID INT,
	ENTDATE DATE,
	RETDATE DATE,
	FOREIGN KEY(PHOTOID) REFERENCES PHOTO(ID),
	FOREIGN KEY(POSTID) REFERENCES POST(ID)
);