DROP TABLE IF EXISTS EMPLOYEE;
DROP TABLE IF EXISTS POST;
DROP TABLE IF EXISTS PHOTO;

CREATE TABLE POST(
	ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL
);

CREATE TABLE PHOTO(
	ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	CONTENTTYPE VARCHAR(40) NOT NULL,
	PHOTO bytea NOT NULL
);

CREATE TABLE EMPLOYEE(
	ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	EMPID VARCHAR(10) NOT NULL,
	NAME VARCHAR(40) NOT NULL,
	AGE SMALLINT,
	GENDER VARCHAR(8) NOT NULL,
	PHOTOID INTEGER,
	ZIP VARCHAR(10),
	PREF SMALLINT,
	ADDRESS VARCHAR(100),
	POSTID INTEGER,
	ENTDATE DATE,
	RETDATE DATE,
	FOREIGN KEY(PHOTOID) REFERENCES PHOTO(ID),
	FOREIGN KEY(POSTID) REFERENCES POST(ID)
);